language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pngcheck
install:
  - pip install -e .
  - pip install -r requirements.txt
script:
  - python cute.py test
